const columns: Column[] = [
	{
		name: 'manufacturer',
		required: true,
		label: 'Производитель',
		field: 'manufacturer',
		sortable: true,
		align: 'left',
		use: true,
	},
	{
		name: 'model',
		required: true,
		label: 'Модель',
		field: 'model',
		sortable: true,
		align: 'left',
		use: true,
	},
	{
		name: 'voltage',
		required: true,
		label: 'Класс напряжения',
		field: 'voltage',
		sortable: true,
		align: 'center',
		use: true,
	},
	{
		name: 'phase',
		required: true,
		label: 'Фазы',
		field: 'phase',
		sortable: true,
		align: 'center',
		use: true,
	},
	{
		name: 'polus',
		required: true,
		label: 'Полюса',
		field: 'polus',
		sortable: true,
		align: 'center',
		use: true,
	},
	{
		name: 'break',
		required: true,
		label: 'Разрывы на полюс',
		field: 'break',
		sortable: true,
		align: 'center',
		use: true,
	},
	{
		name: 'typP',
		required: true,
		label: 'Тип привода',
		field: 'typP',
		sortable: true,
		align: 'left',
		use: true,
	},
	{
		name: 'typB',
		required: true,
		label: 'Тип ВВ',
		field: 'typB',
		sortable: true,
		align: 'left',
		use: true,
	},
]

const rows = [
	{
		id: 0,
		manufacturer: 'ООО "ЭТМ"',
		model: 'МКР-110В-1000-200',
		voltage: 110,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 1,
		manufacturer: 'Уралэлектротяжмаш',
		model: 'ПКВ-220В-1500-200',
		voltage: 220,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 2,
		manufacturer: 'СпецАвтоматика',
		model: 'МКР-110В-1000-200',
		voltage: 110,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 3,
		manufacturer: 'Уралэлектротяжмаш',
		model: 'МКР-110В-1000-200',
		voltage: 110,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 4,
		manufacturer: 'СпецАвтоматика',
		model: 'ПКВ-220В-1500-200',
		voltage: 220,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 5,
		manufacturer: 'СпецАвтоматика',
		model: 'МКР-110В-1000-200',
		voltage: 110,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
		class: 'warn',
	},
	{
		id: 6,
		manufacturer: 'Уралэлектротяжмаш',
		model: 'МКР-220В-1500-200',
		voltage: 220,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 7,
		manufacturer: 'ООО "ЭТМ"',
		model: 'ПКВ-220В-1500-200',
		voltage: 220,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
		class: 'pink',
	},
	{
		id: 8,
		manufacturer: 'ООО "ЭТМ"',
		model: 'ПКВ-220В-1500-200',
		voltage: 220,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 9,
		manufacturer: 'СпецАвтоматика',
		model: 'МКР-110В-1000-200',
		voltage: 110,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 10,
		manufacturer: 'Уралэлектротяжмаш',
		model: 'ПКВ-110В-1000-200',
		voltage: 110,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 11,
		manufacturer: 'ООО "ЭТМ"',
		model: 'МКР-220В-1500-200',
		voltage: 220,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 12,
		manufacturer: 'Уралэлектротяжмаш',
		model: 'МКР-220В-1500-200',
		voltage: 220,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 13,
		manufacturer: 'Уралэлектротяжмаш',
		model: 'МКР-110В-1000-200',
		voltage: 110,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 14,
		manufacturer: 'СпецАвтоматика',
		model: 'ПКВ-110В-1000-200',
		voltage: 110,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 15,
		manufacturer: 'ООО "ЭТМ"',
		model: 'МКР-220В-1500-200',
		voltage: 220,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 16,
		manufacturer: 'ООО "ЭТМ"',
		model: 'МКР-110В-1000-200',
		voltage: 110,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 17,
		manufacturer: 'СпецАвтоматика',
		model: 'ПКВ-220В-1500-200',
		voltage: 220,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 18,
		manufacturer: 'Уралэлектротяжмаш',
		model: 'МКР-110В-1000-200',
		voltage: 110,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 19,
		manufacturer: 'ООО "ЭТМ"',
		model: 'ПКВ-110В-1000-200',
		voltage: 110,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
	{
		id: 20,
		manufacturer: 'Уралэлектротяжмаш',
		model: 'МКР-110В-1000-200',
		voltage: 110,
		phase: 3,
		polus: 1,
		break: 2,
		typP: 'Электромагнитный',
		typB: 'Масляный',
	},
]

const measureColumn = [
	{
		id: 0,
		name: 'time',
		required: true,
		label: 'Время измерения',
		field: 'time',
		sortable: true,
		align: 'left',
		use: true,
	},
	{
		id: 1,
		name: 'parameter 1',
		required: true,
		label: 'Параметр 1',
		field: 'parameter 1',
		sortable: true,
		align: 'left',
		use: true,
	},
	{
		id: 2,
		name: 'parameter 2',
		required: true,
		label: 'Параметр 2',
		field: 'parameter 2',
		sortable: true,
		align: 'left',
		use: true,
	},
	{
		id: 3,
		name: 'parameter 3',
		required: true,
		label: 'Параметр 3',
		field: 'parameter 3',
		sortable: true,
		align: 'left',
		use: true,
	},
	{
		id: 4,
		name: 'parameter 4',
		required: true,
		label: 'Параметр 4',
		field: 'parameter 4',
		sortable: true,
		align: 'left',
		use: true,
	},
	{
		id: 5,
		name: 'parameter 5',
		required: true,
		label: 'Параметр 5',
		field: 'parameter 5',
		sortable: true,
		align: 'left',
		use: true,
	},
	{
		id: 6,
		name: 'parameter 6',
		required: true,
		label: 'Параметр 6',
		field: 'parameter 6',
		sortable: true,
		align: 'left',
		use: true,
	},
	{
		id: 7,
		name: 'parameter 7',
		required: true,
		label: 'Параметр 7',
		field: 'parameter 7',
		sortable: true,
		align: 'left',
		use: true,
	},
	{
		id: 8,
		name: 'parameter 8',
		required: true,
		label: 'Параметр 8',
		field: 'parameter 8',
		sortable: true,
		align: 'left',
		use: true,
	},
	{
		id: 9,
		name: 'parameter 9',
		required: true,
		label: 'Параметр 9',
		field: 'parameter 9',
		sortable: true,
		align: 'left',
		use: true,
	},
	{
		id: 10,
		name: 'parameter 10',
		required: true,
		label: 'Параметр 10',
		field: 'parameter 10',
		sortable: true,
		align: 'left',
		use: true,
	},
]
export { columns, rows, measureColumn }
